# Banco de Dados
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Groq via Spring AI
spring.ai.openai.base-url=${SPRING_AI_OPENAI_BASE_URL}
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.chat.options.model=${SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL}
spring.ai.openai.audio.transcription.options.model=${SPRING_AI_OPENAI_AUDIO_TRANSCRIPTION_OPTIONS_MODEL}

# Telegram Bot
telegram.bot.token=${TELEGRAM_BOT_TOKEN}